packages:
  - "."

allowBuilds:
  bufferutil: true
  keccak: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@smithy/core@3.29.8'
  - '@smithy/credential-provider-imds@4.4.13'
  - '@smithy/fetch-http-handler@5.6.10'
  - '@smithy/node-http-handler@4.9.10'
  - '@smithy/signature-v4@5.6.9'
